/// ------------------------------------------------------------------------------
/// <auto-generated>
/// This file is generated by TableClassGenerator. DO NOT EDIT IT.
/// Source: ui_panels.json
/// </auto-generated>
/// ------------------------------------------------------------------------------

using Newtonsoft.Json;
using System.Collections.Generic;

namespace XGame.Configs
{
    [System.Serializable]
    public class ConfigUiPanels : IConfig
    {
        [JsonProperty("id")]
        public int Id { get; set; }
        
        [JsonProperty("address")]
        public string Address { get; set; }
        
        [JsonProperty("parent_layer")]
        public string ParentLayer { get; set; }
        
    }

    [System.Serializable]
    public class TableUiPanels
    {
        public Dictionary<int, ConfigUiPanels> Configs;

        public ConfigUiPanels GetConfigById(int id)
        {
            return Configs.TryGetValue(id, out var config) ? config : null;
        }
    }
}
